### ISSUE TITLE
tar_embed_list dim seems wrong

### ISSUE THREAD

**Issue by Hyperion-shuo** [tencent-ailab/hokoff#1]
![image](https://github.com/tencent-ailab/hokoff/assets/55169296/f38b9e63-a70b-4aeb-8a3a-1bca20a69afc)
![image](https://github.com/tencent-ailab/hokoff/assets/55169296/8e8707c6-af8f-411f-a329-446da406ca07)

tar_embed_list's dim seems larger than 8, maybe soldier_2_concat_result insdead of fc3_soldier_result be added into tar_embed_list?

**Comment by cloud-qu** [comment]
Hello, thank you for your feedback. The tar_embed_list consists of [none_target, self, enemy, 4 nearest soldiers, nearest tower], which matches the dimensions in target head in action space. You can refer to https://aiarena.tencent.com/hok/doc/environments/index.html#action-spaces for details.
