### ISSUE TITLE
采样脚本运行出错

### ISSUE THREAD

**Issue by silenthou** [tencent-ailab/hokoff#4]
在执行bash start_sample.sh 1,1 1 1 1v1version1 pytorch norm_medium时，到了actor.py中的_, r, d, state_dict = self.env.reset(env_config, use_common_ai=use_common_ai, eval=eval)没有再执行下去了，log的内容如下：
![1731067139639](https://github.com/user-attachments/assets/38deb810-03fb-49c6-91f2-dd85ff09c927)

**Comment by cloud-qu** [comment]
应该是gamecore配置或连接有问题。请检查gamecore镜像配置是否正确(参考[hok_env](https://github.com/tencent-ailab/hok_env/blob/master/docs/run_windows_gamecore_on_linux.md)）以及port是否对应。

**Comment by YOUNG-fnxm** [comment]
I'm also having the same issue, please have you solved it

**Comment by silenthou** [comment]
执行docker build -f ./dockerfile/dockerfile.gamecore -t hok1v1_gamecore --build-arg=BASE_IMAGE=tencentailab/hok_env:cpu_v2.0.1 .
在docker中 hok_env中的步骤都能跑通
![image](https://github.com/user-attachments/assets/1beffed8-112e-4d7e-821c-93874903fc80)

指定端口启动docker，在docker内也能跑通
![image](https://github.com/user-attachments/assets/60ed4458-1c0d-470b-835f-4ec37f43e278)

但是在docker外部python3.8 test_env.py没有响应，所以整个环境，包括(hokoff)都要在docker内部吗？
![image](https://github.com/user-attachments/assets/71330b3d-f56a-4efd-8283-c7e434e94c26)

**Comment by silenthou** [comment]
考虑到上面的这个情况，我直接在docker内  部署了hokoff，把sample中的GC_SERVER的端口换成23432  然后执行脚本，然后就是最开始的问题了。。。

**Comment by TimerChen** [comment]
I create a pull request #6 for this bug.

**Comment by silenthou** [comment]
@TimerChen @cloud-qu  非常感谢你的回复，现在sample脚本能正常运行了，但是我还有一个疑问。
在执行bash start_sample.sh 1,1 10 10 1v1version1 pytorch norm_medium时
我的actor0.log仍然会提示错误
![image](https://github.com/user-attachments/assets/b533f95b-cd5f-46cf-ab15-50b43f4417da)

但是其余的actor.log正常和gamecore交互
![image](https://github.com/user-attachments/assets/4482ec47-3157-4715-9e8d-c086b14670d3)
请问这种情况正常吗？

另外，关于offline_eval
![image](https://github.com/user-attachments/assets/ca1b2c07-6092-4d1f-9d1c-b10248c4ee90)

程序好像总是陷入这个循环中无法正常退出
![image](https://github.com/user-attachments/assets/1b7a274f-2a21-4e78-88a7-c9464fccf654)
请问是哪里没有配置正确呢？

**Comment by TimerChen** [comment]
For the first case, try to debug with one worker. I didn't notice this problem before.
I also have no idea about the second problem.You can try to comment 'unset USE_ZMQ_CURVE' in evaluation.sh.
