### ISSUE TITLE
There was a problem with the evalution

### ISSUE THREAD

**Issue by YOUNG-fnxm** [tencent-ailab/hokoff#5]
When I evaluate the model in hok1v1, I get an error with the zmq server
![image](https://github.com/user-attachments/assets/4e10e0fb-ac8d-4c79-87c1-5c304fec1bad)
![image](https://github.com/user-attachments/assets/575a95f4-e3ac-4eeb-b548-27e856fd78b0)
This is really bothering me, please how can I fix it

**Comment by YOUNG-fnxm** [comment]
I'm running gamecore on Windows and successfully connected to gamecore via test_env.py, but the same configuration has problems with hokoff's evaluation。
![image](https://github.com/user-attachments/assets/046c6190-dabd-4e43-b5f4-1c5930330c97)

**Comment by silenthou** [comment]
你好，请问你解决了这个问题吗？我在sample时也有同样的问题。

**Comment by YOUNG-fnxm** [comment]
> 你好，请问你解决了这个问题吗？我在sample时也有同样的问题。

I've given up on running gamecore on windows, I'm trying to build gamecore on linux via docker, hopefully this will work

**Comment by silenthou** [comment]
我在docker和windows下都尝试了，都不太行

**Comment by YOUNG-fnxm** [comment]
> 我在docker和windows下都尝试了，都不太行

Yes, I also tried to run gamecore with docker but it failed, it's a frustrating bug @cloud-qu

**Comment by silenthou** [comment]
你试过不使用hokoff，直接用hok_env提供的那篇文档cluster.md训练吗？
因为我刚接触强化学习，hok_env怎么加载模型，怎么训练我都不太清楚。
如果可以的话，能加个qq交流一下吗?
3306756675

**Comment by YOUNG-fnxm** [comment]
Now I've found a new issue where the first time I listen on the port, the server responds successfully, but it still gets stuck
![image](https://github.com/user-attachments/assets/882080cf-cd0e-4a12-8f02-ef8cef5349de)

But when I terminate the program and reconnect, the previous Exception: zmq_server. Reset failed: -7, retry 5/5 error

It is worth noting that every time you change the port as shown in the figure, you can receive a response from the server, but you cannot continue to execute it
![image](https://github.com/user-attachments/assets/6d02c6dc-b8ed-4298-a6c0-9743c3118be8)

**Comment by TimerChen** [comment]
I create a pull request #6 for this bug.

**Comment by YOUNG-fnxm** [comment]
> I create a pull request #6 for this bug.

Thanks to your help, I have been able to run the program successfully
